// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A game this Prefixr is launching or running, for the frontend to pick
 * its state back up after the webview reloaded (the launch events it
 * tracks that state from are gone by then).
 */
export type ActiveGame = { id: string, 
/**
 * The process runs; otherwise it's still being prepared.
 */
running: boolean, };
