// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command's user-facing error. `Other` carries pre-formatted text exactly
 * as before (mostly technical/OS errors, e.g. "Could not read X: <os
 * err>") — the frontend shows those as-is, unlocalized, same as today.
 * The other variants carry just the data the situation needs, so the
 * frontend can render the sentence in the UI's current language (see
 * `backendError()` in `src/lib/i18n`). Add a variant here — and a matching
 * `backendErrors_<code>` message in `messages/{de,en}.json` whose
 * placeholders are the variant's fields — for any error a user can
 * plausibly hit and should read in their chosen language, rather than
 * leaving it to fall through to `Other`. `every_app_error_has_a_text`
 * checks that the message exists.
 */
export type AppError = { "code": "other", message: string, } | { "code": "game_already_running" } | { "code": "game_running" } | { "code": "prefix_in_use", game_name: string, } | { "code": "steam_command_not_found" } | { "code": "steam_shutdown_timed_out" } | { "code": "steam_only_flatpak" } | { "code": "steam_not_found" } | { "code": "no_steam_account_found" } | { "code": "shortcuts_vdf_unreadable", error: string, } | { "code": "no_packages_selected" } | { "code": "unclosed_quote_in_launch_args" } | { "code": "pkexec_not_installed", command: string, } | { "code": "sysctl_change_failed", status: string, } | { "code": "runner_in_use", runner_name: string, games: string, } | { "code": "with_log_details", message: string, log_path: string, } | { "code": "winetricks_failed", status: string, log_path: string, } | { "code": "prefix_already_exists", path: string, } | { "code": "path_not_a_directory", path: string, } | { "code": "prefix_dir_not_empty", path: string, } | { "code": "runner_already_exists", tag: string, } | { "code": "git_hub_rate_limited" } | { "code": "git_hub_api_error", status: string, } | { "code": "tool_launch_failed", tool: string, error: string, } | { "code": "setup_launch_failed", error: string, log_path: string, } | { "code": "unknown_wine_tool", tool: string, };
