// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Steam's artwork slots besides the cover and icon, picked from
 * SteamGridDB just like those two.
 */
export type ArtworkKind = "wide" | "hero" | "logo";
