// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An `.exe` shortcut target found among the `.lnk` files an installer
 * created inside a prefix's Desktop/Start Menu, used to guess which exe is
 * the actual game once its installer has finished (see `run_installer` in
 * `commands::games`).
 */
export type DetectedShortcut = { 
/**
 * The shortcut's own file name, without the `.lnk` extension — e.g.
 * "Baldur's Gate 3".
 */
name: string, exe_path: string, };
