// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cached layer, as shown in the runner settings.
 */
export type DirectXLayerStatus = { label: string, installed: boolean, 
/**
 * The release tag it came from; `None` for a copy cached before the
 * tag was recorded.
 */
version: string | null, };
