// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameOverrides } from "./GameOverrides";

/**
 * Payload for `add_game`; the id is assigned by the backend.
 */
export type GameInput = { name: string, exe_path: string, prefix_path: string, runner_id: string, env_vars: { [key in string]: string }, launch_args: string, umu_id: string | null, umu_store: string | null, overrides: GameOverrides, };
