// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wraps the game in `gamescope`, giving it its own nested compositor
 * session with independent resolution/refresh-rate — useful on
 * handhelds/TVs. No-op if `gamescope` isn't installed, and skipped entirely
 * if we're already running inside a gamescope session ourselves (nesting it
 * again is pointless). See `launch_game`.
 */
export type GamescopeSettings = { enabled: boolean, width: number | null, height: number | null, fps_limit: number | null, fullscreen: boolean, };
