// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtworkKind } from "./ArtworkKind";
import type { GameOverrides } from "./GameOverrides";

/**
 * A game the user has added to the library.
 */
export type Game = { id: string, name: string, exe_path: string, prefix_path: string, runner_id: string, env_vars: { [key in string]: string }, 
/**
 * Extra arguments passed to the game's exe itself (e.g. `--launcher-skip
 * -dx11`), analogous to PortProton's `LAUNCH_PARAMETERS`. Split at
 * launch time by `split_launch_args`.
 */
launch_args: string, 
/**
 * The path of the exe's embedded icon, saved as a PNG (see
 * `icons::exe_icon_path`), which the frontend loads through the asset
 * protocol. Extracted once when the game is added/updated; `None` if
 * the exe has no icon resource or it couldn't be parsed. Never written
 * to `config.json`, where versions before the file kept the icon
 * itself as a `data:` URI (see `config::load_icons`).
 */
icon: string | null, 
/**
 * The matched SteamGridDB *game* id, so re-opening the cover picker (or
 * a future Steam-shortcut export) can reuse the match without
 * re-searching by name.
 */
steamgriddb_id: number | null, 
/**
 * The specific SteamGridDB grid asset id behind `cover_url`, kept for
 * future reuse (e.g. a Steam shortcut export).
 */
cover_grid_id: number | null, 
/**
 * Source URL of the chosen SteamGridDB cover image. Its file extension
 * also identifies the cached file's format at
 * `artwork/{id}.{ext}` under the app data dir — see
 * `commands::steamgriddb`.
 */
cover_url: string | null, 
/**
 * The specific SteamGridDB icon asset id behind `steamgriddb_icon_url`,
 * kept for future reuse (e.g. a Steam shortcut export).
 */
steamgriddb_icon_grid_id: number | null, 
/**
 * Source URL of the chosen SteamGridDB icon image (distinct from
 * `icon`, which is extracted from the exe itself). Cached at
 * `artwork/{id}_icon.{ext}` under the app data dir — see
 * `commands::steamgriddb`.
 */
steamgriddb_icon_url: string | null, 
/**
 * Chosen SteamGridDB images for Steam's other artwork slots, by kind:
 * the source URL, cached at `artwork/{id}{suffix}.{ext}` (see
 * `ArtworkKind::cache_suffix`). Only used by the Steam export.
 */
artwork: { [key in ArtworkKind]?: string }, 
/**
 * The game's UMU id (e.g. `umu-1091500`), passed to umu as `GAMEID` so
 * umu-protonfixes applies this game's own fixes, and Proton its
 * per-game hacks (umu derives `SteamAppId` from it). `None` leaves umu
 * at `umu-default`, i.e. only the generic fixes. Proton runners only.
 */
umu_id: string | null, 
/**
 * The store the `umu_id` entry belongs to (`gog`, `egs`, …), passed as
 * `STORE`: protonfixes then looks in that store's fix folder instead of
 * the generic umu one.
 */
umu_store: string | null, 
/**
 * Per-game deviations from the global MangoHud/performance settings.
 * Defaults to "inherit everything", so games from older configs behave
 * exactly as before.
 */
overrides: GameOverrides, };
