// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphicsOverrides } from "./GraphicsOverrides";
import type { OverlayOverrides } from "./OverlayOverrides";
import type { PerformanceOverrides } from "./PerformanceOverrides";

/**
 * Per-game overrides of the global settings, one block per category. Every
 * field is `None` (or, for Proton, a missing key) to inherit the global
 * setting.
 */
export type GameOverrides = { performance: PerformanceOverrides, graphics: GraphicsOverrides, overlay: OverlayOverrides, 
/**
 * `PROTON_*` variable → on/off, layered key by key over
 * `ProtonConfig::options`.
 */
proton: { [key in string]: boolean }, };
