// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub settings — see `commands::github`. An optional personal access
 * token, sent as a bearer token on requests to `api.github.com` (runner
 * release listings) to raise its rate limit from 60 to 5000 requests/hour;
 * GitHub accepts unauthenticated requests too, so this stays optional.
 */
export type GitHubConfig = { token: string | null, };
