// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GamescopeSettings } from "./GamescopeSettings";
import type { VkBasaltSettings } from "./VkBasaltSettings";

/**
 * gamescope and vkBasalt are overridden as a whole block rather than field
 * by field: a global `gamescope.width: None` already means "native", so
 * per-field options couldn't tell "inherit the width" apart from
 * "explicitly no width".
 */
export type GraphicsOverrides = { gamescope: GamescopeSettings | null, vkbasalt: VkBasaltSettings | null, };
