// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GamescopeSettings } from "./GamescopeSettings";
import type { VkBasaltSettings } from "./VkBasaltSettings";

/**
 * Bild: what the game's output goes through on its way to the screen.
 */
export type GraphicsConfig = { gamescope: GamescopeSettings, vkbasalt: VkBasaltSettings, };
