// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedShortcut } from "./DetectedShortcut";

/**
 * What `run_installer` reports back once the installer exited.
 */
export type InstallerResult = { shortcuts: Array<DetectedShortcut>, log_path: string, };
