// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MangoHudLayout = { preset: string, position: "top-left" | "top-right" | "bottom-left" | "bottom-right", theme_color: string, background_alpha: number, round_corners: boolean, show_fps: boolean, show_frametime: boolean, show_cpu: boolean, show_gpu: boolean, show_ram: boolean, show_vram: boolean, show_temps: boolean, 
/**
 * Small on/off indicator icons for other tools in the stack.
 */
show_gamemode: boolean, show_vkbasalt: boolean, show_hdr: boolean, 
/**
 * Static diagnostic info, handy since this app manages the runner and
 * DXVK/VKD3D build a game actually ends up using (see
 * `graphics_layers.rs`) — `show_engine_version` in particular surfaces
 * the DXVK/VKD3D version MangoHud detects at runtime.
 */
show_driver: boolean, show_engine_version: boolean, show_wine: boolean, show_gpu_name: boolean, show_resolution: boolean, 
/**
 * Lays the stats out in a row instead of a column (MangoHud's
 * `horizontal` option).
 */
horizontal: boolean, };
