// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MaxMapCountStatus = { current: number, recommended: number, sufficient: boolean, 
/**
 * Whether `fix_max_map_count` can actually be offered — it shells out to
 * `pkexec` for the privilege escalation, which isn't guaranteed to be
 * installed (e.g. minimal window-manager-only setups without a
 * PolicyKit agent). The frontend falls back to showing the equivalent
 * shell command for the user to run manually when this is `false`.
 */
can_fix: boolean, };
