// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MangoHudLayout } from "./MangoHudLayout";

/**
 * On/off separately from the look, so a game can switch MangoHud off (or
 * on) while still following the global layout.
 */
export type OverlayOverrides = { enabled: boolean | null, layout: MangoHudLayout | null, };
