// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Leistung: toggles that change how the system treats a running game.
 * Kept opt-in (all off by default), since we can't know whether the
 * underlying tool is even installed, so nothing gets silently switched on.
 */
export type PerformanceConfig = { gamemode_enabled: boolean, 
/**
 * Holds the desktop's power-profiles-daemon at the "performance" profile
 * for the duration of the game (via `powerprofilesctl launch`), released
 * automatically on exit. GameMode does *not* reliably do this itself —
 * it writes the CPU governor directly, which power-profiles-daemon (the
 * governor owner on most modern distros) can just overwrite again, so
 * `gamemoderun` alone often leaves the profile on "balanced". See
 * `launch_game`.
 */
power_profile_enabled: boolean, 
/**
 * Wraps the game process with `systemd-inhibit` so the screensaver/sleep
 * don't kick in mid-session. No-op if `systemd-inhibit` or the D-Bus
 * system bus isn't available.
 */
inhibit_sleep_enabled: boolean, };
