// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerformanceOverrides = { gamemode_enabled: boolean | null, power_profile_enabled: boolean | null, inhibit_sleep_enabled: boolean | null, };
