// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Wine prefix known to the app, tracked in the config file. Not tied to a
 * runner — the runner that (lazily) initializes it is decided per-game, via
 * `Game::runner_id`.
 */
export type PrefixInfo = { path: string, };
