// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One on/off option a Proton build's `proton` script reads from the
 * environment. `env` is the variable to set; `aliases` are further names the
 * script accepts for the same `config` flag (e.g. `PROTON_USE_HDR` next to
 * `PROTON_ENABLE_HDR`), listed so the UI can tell they're the same switch.
 */
export type ProtonOption = { env: string, config: string, aliases: Array<string>, };
