// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proton: `PROTON_*` switches (see `commands::proton_options`) set for every
 * game on a Proton runner, keyed by variable name; a missing key leaves
 * Proton's own default.
 */
export type ProtonConfig = { options: { [key in string]: boolean }, };
