// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A downloadable runner build, as surfaced to the frontend.
 */
export type RunnerRelease = { source: string, tag: string, name: string, published_at: string, download_url: string, size: number, };
