// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of compatibility layer a runner provides.
 */
export type RunnerKind = "proton" | "wine";
