// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunnerKind } from "./RunnerKind";

/**
 * A runner source as surfaced to the frontend, to drive the source picker
 * without duplicating labels/kinds on the TypeScript side.
 */
export type RunnerSourceInfo = { id: string, label: string, kind: RunnerKind, };
