// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunnerKind } from "./RunnerKind";

/**
 * A Proton or Wine build discovered on disk under the configured runners directory.
 * `id` is the folder name and doubles as the stable identifier used elsewhere
 * (e.g. `Game::runner_id`).
 */
export type Runner = { id: string, name: string, path: string, kind: RunnerKind, };
