// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A SteamGridDB image asset option (a grid/cover or an icon), as surfaced
 * to the frontend.
 */
export type SteamGridDbGrid = { id: number, url: string, thumb: string, width: number, height: number, };
