// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A SteamGridDB game search match, as surfaced to the frontend.
 */
export type SteamGridDbGameMatch = { id: number, name: string, verified: boolean, };
