// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SteamGridDB API settings — see `commands::steamgriddb`.
 */
export type SteamGridDbConfig = { api_key: string | null, };
