// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SteamChange = { "status": "done", restarted_steam: boolean, } | { "status": "steam_running" };
