// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a suggestion came from.
 */
export type UmuMatchSource = "steam" | "database";
