// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UmuMatchSource } from "./UmuMatchSource";

/**
 * A suggested UMU id for a game, as surfaced to the frontend.
 */
export type UmuMatch = { umu_id: string, title: string, 
/**
 * The store this entry is for (`gog`, `egs`, …); `None` for Steam and
 * standalone releases.
 */
store: string | null, source: UmuMatchSource, };
