// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UmuStatus = { installed: boolean, 
/**
 * The GitHub release tag the installed copy came from.
 */
version: string | null, };
