// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * vkBasalt post-processing — see `commands::graphics`.
 */
export type VkBasaltSettings = { enabled: boolean, sharpen: boolean, sharpness: number, smaa: boolean, };
